'use strict';

/**
 * Role-Based Access Control (RBAC) Permission Matrix
 * Defines distinct roles and their atomic permissions across all CRM modules.
 */

const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  COUNSELOR: 'counselor',
  INSTRUCTOR: 'instructor',
  FINANCE_OFFICER: 'finance_officer',
  STUDENT: 'student',
  PARENT: 'parent'
};

const PERMISSIONS = {
  // Authentication & Profile
  AUTH_LOGIN: 'auth:login',
  AUTH_MANAGE_USERS: 'auth:manage_users',
  AUTH_VIEW_AUDIT_LOGS: 'auth:view_audit_logs',

  // Lead Management
  LEADS_VIEW: 'leads:view',
  LEADS_VIEW_ALL: 'leads:view_all',
  LEADS_CREATE: 'leads:create',
  LEADS_EDIT: 'leads:edit',
  LEADS_DELETE: 'leads:delete',
  LEADS_ASSIGN: 'leads:assign',
  LEADS_CHANGE_STAGE: 'leads:change_stage',
  LEADS_LOG_CALL: 'leads:log_call',
  LEADS_EXPORT: 'leads:export',

  // Admissions
  ADMISSIONS_VIEW: 'admissions:view',
  ADMISSIONS_REVIEW: 'admissions:review',
  ADMISSIONS_APPROVE: 'admissions:approve',
  ADMISSIONS_REJECT: 'admissions:reject',
  ADMISSIONS_CREATE_OFFER: 'admissions:create_offer',

  // Course Management
  COURSES_VIEW: 'courses:view',
  COURSES_CREATE: 'courses:create',
  COURSES_EDIT: 'courses:edit',
  COURSES_DELETE: 'courses:delete',
  BATCHES_MANAGE: 'batches:manage',

  // Student Information System
  STUDENTS_VIEW: 'students:view',
  STUDENTS_VIEW_ALL: 'students:view_all',
  STUDENTS_CREATE: 'students:create',
  STUDENTS_EDIT: 'students:edit',
  STUDENTS_DELETE: 'students:delete',
  STUDENTS_VIEW_PROFILE: 'students:view_profile',

  // Academic (Attendance & Grades)
  ATTENDANCE_VIEW: 'attendance:view',
  ATTENDANCE_MARK: 'attendance:mark',
  ATTENDANCE_EDIT: 'attendance:edit',
  GRADES_VIEW: 'grades:view',
  GRADES_ENTER: 'grades:enter',
  GRADES_PUBLISH: 'grades:publish',
  TRANSCRIPTS_GENERATE: 'transcripts:generate',

  // Finance & Invoicing
  FINANCE_VIEW: 'finance:view',
  FINANCE_INVOICE_CREATE: 'finance:invoice_create',
  FINANCE_INVOICE_EDIT: 'finance:invoice_edit',
  FINANCE_PAYMENT_RECORD: 'finance:payment_record',
  FINANCE_DISCOUNT_APPLY: 'finance:discount_apply',
  FINANCE_REPORTS: 'finance:reports',

  // Support Helpdesk
  TICKETS_VIEW_OWN: 'tickets:view_own',
  TICKETS_VIEW_ALL: 'tickets:view_all',
  TICKETS_CREATE: 'tickets:create',
  TICKETS_REPLY: 'tickets:reply',
  TICKETS_ASSIGN: 'tickets:assign',
  TICKETS_RESOLVE: 'tickets:resolve',
  TICKETS_CLOSE: 'tickets:close',

  // Communications & Notifications
  NOTIFICATIONS_VIEW: 'notifications:view',
  NOTIFICATIONS_BROADCAST: 'notifications:broadcast',
  ANNOUNCEMENTS_MANAGE: 'announcements:manage',

  // Analytics & Reporting
  ANALYTICS_VIEW_DASHBOARD: 'analytics:view_dashboard',
  ANALYTICS_FINANCIAL: 'analytics:financial',
  ANALYTICS_ACADEMIC: 'analytics:academic',
  ANALYTICS_CONVERSION: 'analytics:conversion',
  REPORTS_EXPORT: 'reports:export',

  // System Settings
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_MANAGE: 'settings:manage'
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_MANAGE_USERS,
    PERMISSIONS.AUTH_VIEW_AUDIT_LOGS,
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_VIEW_ALL,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.LEADS_DELETE,
    PERMISSIONS.LEADS_ASSIGN,
    PERMISSIONS.LEADS_CHANGE_STAGE,
    PERMISSIONS.LEADS_LOG_CALL,
    PERMISSIONS.LEADS_EXPORT,
    PERMISSIONS.ADMISSIONS_VIEW,
    PERMISSIONS.ADMISSIONS_REVIEW,
    PERMISSIONS.ADMISSIONS_APPROVE,
    PERMISSIONS.ADMISSIONS_REJECT,
    PERMISSIONS.ADMISSIONS_CREATE_OFFER,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_EDIT,
    PERMISSIONS.COURSES_DELETE,
    PERMISSIONS.BATCHES_MANAGE,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_VIEW_ALL,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_EDIT,
    PERMISSIONS.STUDENTS_DELETE,
    PERMISSIONS.STUDENTS_VIEW_PROFILE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_EDIT,
    PERMISSIONS.GRADES_VIEW,
    PERMISSIONS.GRADES_ENTER,
    PERMISSIONS.GRADES_PUBLISH,
    PERMISSIONS.TRANSCRIPTS_GENERATE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_INVOICE_CREATE,
    PERMISSIONS.FINANCE_INVOICE_EDIT,
    PERMISSIONS.FINANCE_PAYMENT_RECORD,
    PERMISSIONS.FINANCE_DISCOUNT_APPLY,
    PERMISSIONS.FINANCE_REPORTS,
    PERMISSIONS.TICKETS_VIEW_OWN,
    PERMISSIONS.TICKETS_VIEW_ALL,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_REPLY,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.TICKETS_RESOLVE,
    PERMISSIONS.TICKETS_CLOSE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_BROADCAST,
    PERMISSIONS.ANNOUNCEMENTS_MANAGE,
    PERMISSIONS.ANALYTICS_VIEW_DASHBOARD,
    PERMISSIONS.ANALYTICS_FINANCIAL,
    PERMISSIONS.ANALYTICS_ACADEMIC,
    PERMISSIONS.ANALYTICS_CONVERSION,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE
  ],

  [ROLES.COUNSELOR]: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_VIEW_ALL,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.LEADS_CHANGE_STAGE,
    PERMISSIONS.LEADS_LOG_CALL,
    PERMISSIONS.LEADS_EXPORT,
    PERMISSIONS.ADMISSIONS_VIEW,
    PERMISSIONS.ADMISSIONS_REVIEW,
    PERMISSIONS.ADMISSIONS_CREATE_OFFER,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_VIEW_PROFILE,
    PERMISSIONS.TICKETS_VIEW_OWN,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_REPLY,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW_DASHBOARD,
    PERMISSIONS.ANALYTICS_CONVERSION
  ],

  [ROLES.INSTRUCTOR]: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_VIEW_PROFILE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_EDIT,
    PERMISSIONS.GRADES_VIEW,
    PERMISSIONS.GRADES_ENTER,
    PERMISSIONS.GRADES_PUBLISH,
    PERMISSIONS.TRANSCRIPTS_GENERATE,
    PERMISSIONS.TICKETS_VIEW_OWN,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_REPLY,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW_DASHBOARD,
    PERMISSIONS.ANALYTICS_ACADEMIC
  ],

  [ROLES.FINANCE_OFFICER]: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_VIEW_PROFILE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_INVOICE_CREATE,
    PERMISSIONS.FINANCE_INVOICE_EDIT,
    PERMISSIONS.FINANCE_PAYMENT_RECORD,
    PERMISSIONS.FINANCE_DISCOUNT_APPLY,
    PERMISSIONS.FINANCE_REPORTS,
    PERMISSIONS.TICKETS_VIEW_OWN,
    PERMISSIONS.TICKETS_VIEW_ALL,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_REPLY,
    PERMISSIONS.TICKETS_RESOLVE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW_DASHBOARD,
    PERMISSIONS.ANALYTICS_FINANCIAL,
    PERMISSIONS.REPORTS_EXPORT
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.STUDENTS_VIEW_PROFILE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.GRADES_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.TICKETS_VIEW_OWN,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_REPLY,
    PERMISSIONS.NOTIFICATIONS_VIEW
  ],

  [ROLES.PARENT]: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.STUDENTS_VIEW_PROFILE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.GRADES_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.TICKETS_VIEW_OWN,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_REPLY,
    PERMISSIONS.NOTIFICATIONS_VIEW
  ]
};

function hasPermission(role, permission) {
  if (!role || !ROLE_PERMISSIONS[role]) return false;
  return ROLE_PERMISSIONS[role].includes(permission);
}

function hasAnyPermission(role, permissions = []) {
  if (!role || !ROLE_PERMISSIONS[role]) return false;
  return permissions.some(p => ROLE_PERMISSIONS[role].includes(p));
}

function hasAllPermissions(role, permissions = []) {
  if (!role || !ROLE_PERMISSIONS[role]) return false;
  return permissions.every(p => ROLE_PERMISSIONS[role].includes(p));
}

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions
};
